cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupons/urls.py
from django.urls import path

from . import views


app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name="apply"),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail, 
         name="admin_order_detail"),
]

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, 
                                      coerce=int, label='')
    override = forms.BooleanField(required=False, initial=False, 
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from coupons.forms import CouponApplyForm
from shop.models import Product

from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product, quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect("cart:cart_detail")

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect("cart:cart_detail")

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={
                'quantity': item['quantity'],
                'override': True,
            }
        )
    coupon_apply_form = CouponApplyForm()
    return render(request, "cart/detail.html", {
        'cart': cart,
        'coupon_apply_form': coupon_apply_form,
        })

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Ваш кошик{% endblock  %}

{% block content %}
  <h2>Ваш кошик</h2>
  <table class="striped">
    <thead>
      <tr>
        <th scope="col">Фото</th>
        <th scope="col">Назва</th>
        <th scope="col">Кількість</th>
        <th scope="col">Видалити</th>
        <th scope="col">Ціна за 1 од.</th>
        <th scope="col">Сума</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" width="100">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                <fieldset role="group">
                  {{ item.update_quantity_form.quantity }}
                  {{ item.update_quantity_form.override }}
                  <input type="submit" value="✏️" style="max-width: 35px; padding: 3px;">
                </fieldset>
              </form>
            </td>
            <td>
              <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                <input type="submit" value="❌">
                {% csrf_token %}
              </form>
            </td>
            <td>{{ item.price }}</td>
            <td>{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
    <tfoot>
      {% if cart.coupon %}
      <tr>
        <td>До знижки</td>
        <td colspan="4"></td>
        <td><b>{{ cart.get_total_price|floatformat:2 }}&nbsp;₴</b></td>
      </tr>
      <tr>
        <td>Купон "{{ cart.coupon.code }}" на {{ cart.coupon.discount }}%</td>
        <td colspan="4"></td>
        <td><b>{{ cart.get_discount|floatformat:2 }}&nbsp;₴</b></td>
      </tr>
      {% endif %}
      <tr>
        <td scope="row"><b>Разом:</b></td>
        <td colspan="4"></td>
        <td><b>{{ cart.get_total_price_after_discount|floatformat:2 }}&nbsp;₴</b></td>
      </tr>
    </tfoot>
    </tbody>
  </table>
  <div class="row">
    <div class="col-lg-6">
      <form action="{% url 'coupons:apply' %}" method="post">
        {% csrf_token %}
        {{ coupon_apply_form.as_p }}
        <input type="submit" value="Застосувати">
      </form>
    </div>
    <div class="col-lg-6">
      <p align="right">
        <a href="{% url 'shop:product_list' %}" role="button">Продовжити покупки</a>
      </p>
      <p align="right">
        <a href="{% url 'orders:order_create' %}" role="button">Оформити замовлення</a>
      </p>
    </div>
  </div>
  {% endblock content %}