cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='Назва')
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_list_by_category", args=[self.slug])
    
    

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', 
                                 on_delete=models.CASCADE, verbose_name='Категорія')
    name = models.CharField(max_length=300, verbose_name='Назва')
    slug = models.SlugField(max_length=300)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True, 
                              verbose_name='Зображення')
    description = models.TextField(blank=True, verbose_name='Опис')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Ціна')
    available = models.BooleanField(default=True, verbose_name='В наявності')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Додано')
    updated = models.DateTimeField(auto_now=True, verbose_name='Змінено')

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
        verbose_name = 'Товар'
        verbose_name_plural = 'Товари'

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("shop:product_detail", args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404

from cart.forms import CartAddProductForm

from .models import Category, Product


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    if query := request.GET.get('search'):
        products = (products.filter(name__contains=query) | 
                    products.filter(description__contains=query))
    additional_cards = 3 - products.count() % 3
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products,
                   'additional_cards': additional_cards,
                   'query': query})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', 
                  {'product': product, 'cart_product_form': cart_product_form})

shop/templates/shop/base.html
<!doctype html>
<html lang="uk">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="color-scheme" content="light dark">
    <link 
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
    >
    <link 
      rel="stylesheet" 
      href="https://cdnjs.cloudflare.com/ajax/libs/flexboxgrid/6.3.1/flexboxgrid.min.css"
    >
    <link 
      rel="stylesheet" 
      href="https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css" 
    >
    <title>{% block title %}Літера{% endblock %}</title>
  </head>
  <body>
    <header class="container-fluid">
      <nav>
        <ul>
          <li><h1><a href="/">Літера</a></h1></li>
        </ul>
        <ul>
          <li><a href="{% url 'shop:product_list' %}">Каталог</a></li>
          <li>
            <form method="get">
              <input type="search" name="search" placeholder="Пошук...">
            </form>
          </li>
          {% if request.user.is_authenticated %}
            <li>
              <details class="dropdown">
                <summary>
                  {{ request.user.first_name|default:request.user.username }}
                </summary>
                <ul dir="rtl">
                  <li><a href="{% url 'edit' %}">Профіль</a></li>
                  {% comment %} <li><a href="#">Logout</a></li> {% endcomment %}
                  <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Вихід">
                    <li><a href="{% url 'register' %}">Реєстрація</a></li>
                  </form>
                </ul>
              </details>
            </li>
          {% else %}
            <li><a href="{% url 'login' %}">Вхід</a></li>
          {% endif %}
          <li><a href="{% url 'cart:cart_detail' %}">
            {% with total_items=cart|length %}
              {% if total_items > 0 %}
                <i class="iconoir-cart"></i>
                <span><sup>{{ total_items }}</sup></span>
              {% endif %}
            {% endwith %}
          </a></li>
        </ul>
      </nav>
    </header> 

    <div class="container" id="messages">
      {% for message in messages %}
        <dialog open id="message">
          <article>
            <header>
              <button aria-label="Close" rel="prev" id="close-button"></button>
              <p>
                {% if message.tags == 'error' %}
                  ❌ Помилка
                {% else %}
                  ✅ Успішно
                {% endif %}
              </p>
            </header>
            <p>
              {{ message|safe }}
            </p>
          </article>
        </dialog>
      {% endfor %}
    </div>

    <main class="container">
      <section class="row">
        <div class="col-lg-12">
          {% block content %}
            <article class="box">Каталог товарів</article>
          {% endblock  %}
        </div>
      </section>
    </main>

    <footer class="container-fluid">
      <p align="center">&copy; 2025 Літера</p>
    </footer>

    <script>
      // Cancel button closes the dialog box
      const dialog = document.getElementById("message");
      const cancelButton = document.getElementById("close-button");
      cancelButton.addEventListener("click", () => {
        dialog.close(); // Set dialog.returnValue to null
      });
    </script>
  </body>
</html>